### ISSUE TITLE
Problem 1: JavaScript Date Picker

### ISSUE THREAD

**Issue by ghost** [1213-Throwback/Project_3#2]
For this problem, you will be implementing two interactive DatePicker [displays](https://www.google.com/search?tbm=isch&q=datepicker&gws_rd=ssl#) using a combination of HTML, CSS, and JavaScript.

In your project3 directory create a file DatePicker.js that implements a JavaScript class named DatePicker that can be used as in the following example:

var datePicker = new DatePicker("div1", function (id, fixedDate) {
   console.log("DatePicker with id", id,
       "selected date:", fixedDate.month + "/" + fixedDate.day + "/" + fixedDate.year);
});
datePicker.render(new Date("July 4, 1776"));
datePicker.render(new Date("July 4, 1776"));
The constructor takes an argument consisting of the id attribute for an existing div and a date selection callback function. When a date is selected the callback function should be called with the id argument and an object containing the properties month, day, year with the number encoding of the date (e.g. {month: 1, day: 30, year: 2016} is the encoding of January 30, 2016).

The object should have a render method that takes one argument consisting of a Date object that selects a particular month (the object can refer to any time within the month). When render is invoked it replaces the contents of the date picker's div with HTML that displays a small one-month calendar such as those you might see in a travel reservation website:

The calendar must display the days of the selected month in a grid with one line for each week and one column for each day of the week.
Weeks run from Sunday on the left to Saturday on the right. The calendar must contain a header row displaying abbreviations for the days of the week, such as "Su", "Mo", etc.
Each day of the month is displayed as a number.
Some weeks when displayed in the date picker may contain days not in the selected month. These days should be displayed as the number in their respective month, but in a dimmed fashion to indicate they are not part of the current month.
All weeks displayed should contain at least one day belonging to the current month. Most months will display 5 weeks, but some months may display 4 or 6 depending on the days. The number of rows in your calendar should not be fixed.
The calendar must display the name of the month and year at the top of the calendar. In addition, it must display controls such as "<" and ">" that can be clicked to change the calendar's display to the previous or next month.
Clicking on a valid day of the current month should invoke the callback specified on the constructor with the arguments described above. Clicking on days belonging to months other than the current month should not invoke the callback.
Once you have created the JavaScript class, we have provided a file datepicker.html (you do not need to modify this html file) containing two empty div elements, plus a bit of JavaScript code that invokes the DatePicker class to display a date picker in each of the divs. One of the date pickers initially displays the current month and the other displays the month of January 2009. It should be possible to change the month of each date picker independently using the controls on that date picker.

The provided html file has no styling so please create a stylesheet with the filename datepicker.css to apply styling to the calendars and make them look nice. The corresponding link tag that requires the css file has already been added for you in the html file.

**Comment by DiegoLopezInc** [comment]
Created another issue log with updates on design, problem #1 DONE!!!! 👍
