### ISSUE TITLE
Testing Project_3 problem 1

### ISSUE THREAD

**Issue by ZadokA** [1213-Throwback/Project_3#8]
I intend on testing problem 1 in project 3 to ensure that it fulfills all requirements.

**Comment by Vulcran** [comment]
<img width="426" alt="Screenshot 2023-09-25 at 5 10 37 PM" src="https://github.com/1213-Throwback/Project_3/assets/104237476/e885d9df-3472-44fb-8175-1089f6fb670b">

Fixed all the issues because there was no . at the beginning of the Json file. After that it was just changing alot of lets to const
